pipeline:
  name: custom_remote_pipe3cNlv
  identifier: custom_remote_pipe3cNlv
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: ss
                  identifier: ss
                  template:
                    templateRef: shell_scriptxwSC3
                    versionLabel: v1
        tags: {}
