pipeline:
  name: NGPipeAutoRemoteGitConfigIRdk9Y3A4b
  identifier: NGPipeAutoRemoteGitConfigIRdk9Y3A4b
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoProjectNGGovernance2zGasVt8HF
  tags: { }
  stages:
      - stage:
          name: S1
          identifier: S1
          description: ""
          type: Custom
          spec:
            execution:
              steps:
                - step:
                    type: ShellScript
                    name: Shell Script_1
                    identifier: ShellScript_1
                    spec:
                      shell: Bash
                      onDelegate: true
                      source:
                        type: Inline
                        spec:
                          script: echo 'hi'
                      environmentVariables: [ ]
                      outputVariables: [ ]
                    timeout: 1m
          tags: { }