pipeline:
  name: testHealth
  identifier: testHealth
  projectIdentifier: AmitTest2
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: step1
                  identifier: step1
                  template:
                    templateRef: account.GitsyncTemplate_MvYzU
                    versionLabel: v2
                    templateInputs:
                      type: ShellScript
                      spec:
                        source:
                          type: Inline
                          spec:
                            script: <+input>
        tags: {}
