pipeline:
  name: pipeline_auto_createA8Vxe
  identifier: pipeline_auto_createA8Vxe
  orgIdentifier: Simlified_Git_sync
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  stages:
    - stage:
        identifier: s1
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  identifier: ShellScript_1
                  type: ShellScript
                  spec:
                    source:
                      type: Inline
                      spec:
                        script: echo 'hi'